### ISSUE TITLE
Question about Voice Transcription

### ISSUE THREAD

**Issue by IssacJun** [inspired-futures/ipade#1]
I am using Jitsi-meet and am a beginner.

I have checked your ìpàdé source and its features, and it seems that there are many better features than the existing Jitsi. I am particularly impressed with the Voice Transcription feature. I have several questions in this regard.

1. Did you develop the Voice Transcription feature yourself? 
Or did you develop it using open source? If you developed it with open source, what is the name of that open source?

2. Can ìpàdé store voices in a database such as MySQL separately for each user?

3. Can I use it by duplicating your ìpàdé repository on my PC and configuring a virtual host within the web server of Nginx or Apache, just like the existing ['Jitsi Quick Installation method'](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart)?

**Comment by deleolajide** [comment]
>and it seems that there are many better features than the existing Jitsi.

Thanks for the kind words, but I won't say they are better. They are extra features requested by users of Openfire Meetings. For more details, see my [blog posting](https://discourse.igniterealtime.org/t/openfire-meetings-as-an-alternative-to-zoom/87620)

>Did you develop the Voice Transcription feature yourself?
Or did you develop it using open source? If you developed it with open source, what is the name of that open source?

The voice transcription is a web standard (webkitSpeechRecognition). See code [here](https://github.com/igniterealtime/openfire-pade-plugin/blob/1cd2e19bdb3e88e521fa5cecc62e66ce5c82cbbb/web/src/main/webapp/custom_ofmeet.js#L97)
It currently only works in Chrome browsers for now.

>Can ìpàdé store voices in a database such as MySQL separately for each user?

The voice recording chunks are stored temporary from the browser in the IndexDB database of the browser and then assembled into a webm file. You can add additional code to upload the webm file from the client to an external MySQL DB on a web server.

>Can I use it by duplicating your ìpàdé repository on my PC and configuring a virtual host within the web server of Nginx or Apache, just like the existing 'Jitsi Quick Installation method'?

As I mentioned before, this project ìpàdé is extracted from the Openfire Meetings project which uses Jitsi Meet and Jitsi Videobridge with Openfire XMPP server. It different from the standalone Jitsi solution that uses the Prosody XMPP server. The Jitsi Meet code in ìpàdé was modified to remove dependency on a web server so that it can be used as a static web site on GitHub Pages with any Openfire Meetings service (like pade.chat) or Jitsi Meet service like (meet.jit.si)
