### ISSUE TITLE
How to implement breakout room

### ISSUE THREAD

**Issue by linzeli** [inspired-futures/ipade#3]
Hello, I am a beginner for jitsi meet. I was trying to implement a breakout room in original jitsi meet. Some search took me to this project and I am really impressed by the new functions you have implemented. Therefore I would like some advice on my own implementation. I have two ideas and I want to know which would be more feasible. 

1. Have each breakout room as different meeting and link the different meeting to the page, and put a link on each page. So the attendee can click on the link, they join the selected meeting.
2. Have different attendee in the same meeting, if they click on join room1, only people which also click join room 1 will be unmuted and others will all be muted. 

I also want to have your opinion on how you did it in this project, which file did you change and how does it work.
Sorry for any inconvenience and I am looking forward to your guidance.

**Comment by deleolajide** [comment]
> 1. Have each breakout room as different meeting and link the different meeting to the page, and put a link on each page. So the attendee can click on the link, they join the selected meeting.

This the one I would recomend. You would need to know React in order to modify Jitsi Meet source code. 

I don't use React and work with the minified files directly and reference the React code for understanding. The bulk of my code is the this file - https://github.com/inspired-futures/ipade/blob/master/docs/custom_ofmeet.js

If you want to track my changes, to the jitsi meet code, look for the comments with the letters BAO in the following two files.

https://github.com/inspired-futures/ipade/blob/master/docs/libs/app.bundle.min.js
https://github.com/inspired-futures/ipade/blob/master/docs/libs/lib-jitsi-meet.min.js

**Comment by linzeli** [comment]
Thank you very much for your help.
